const requests = {
	fetchNowPlaying: `/movie/now_playing`,
	fetchTrending: `/trending/all/week`,
	fetchTopRated: `/movie/top_rated`,
	fetchActionMovies: `/discover/movie?with_genres=28`,
	fetchComedyMovies: `/discover/movie?with_genres=35`,
	fetchHorrorMovies: `/discover/movie?with_genres=27`,
	fetchRomanceMovies: `/discover/movie?with_genres=10749`,
	fetchDocumentaries: `/discover/movie?with_genres=99`,
	fetchAdventure: `/discover/movie?with_genres=12`,
	fetchFantasy: `/discover/movie?with_genres=14`,
	fetchHistory: `/discover/movie?with_genres=36`,
	fetchMusic: `/discover/movie?with_genres=10402`,
	fetchWar: `/discover/movie?with_genres=10752`,
	fetchCrime: `/discover/movie?with_genres=80`,
	fetchFamily: `/discover/movie?with_genres=10751`,
	fetchThriller: `/discover/movie?with_genres=53`,
	fetchDrama: `/discover/movie?with_genres=18`,
	fetchMystery: `/discover/movie?with_genres=9648`,
	fetchSciFi: `/discover/movie?with_genres=878`,
	fetchWestern: `/discover/movie?with_genres=37`,
	fetchAnimation: `/discover/movie?with_genres=16`,
	fetchTV: `/discover/movie?with_genres=10770`,
};

export default requests;
